# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: d7293861-6714-4ddf-8032-13e7530e5c88_1760062950598
# Generated: 2025-10-10T02:22:31.109Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-10-11h
# - Full Path: /2025-10-10-11h/OS--Unknown--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 계정 잠금 임계값 설정 점검 스크립트 ===
# 스크립트 ID: U-03
# 카테고리: 계정관리
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# PAM system-auth 경로: /etc/pam.d/system-auth
# 실패 허용 횟수(deny): 5

# 점검 시간
echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: PAM 경로=/etc/pam.d/system-auth, 실패 허용 횟수=5"

# 점검 로직 시작
# 1. PAM 설정 파일 존재 여부 확인
if [ ! -f /etc/pam.d/system-auth ]; then
  echo "1. PAM 설정 파일 존재 여부"
  echo "   [FAIL] /etc/pam.d/system-auth 파일이 존재하지 않습니다."
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: PAM 설정 파일을 확인하고 올바른 경로에 위치시킵니다."
  exit 1
fi

# 2. PAM 설정 파일 읽기 권한 확인
if [ ! -r /etc/pam.d/system-auth ]; then
  echo "2. PAM 설정 파일 읽기 권한 확인"
  echo "   [FAIL] /etc/pam.d/system-auth 파일을 읽을 수 있는 권한이 없습니다."
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: 파일 권한을 확인하고 읽기 권한을 부여합니다."
  exit 1
fi

# 3. 계정 잠금 임계값 설정 확인
deny_value=$(grep -E 'pam_tally2.so.*deny=' /etc/pam.d/system-auth | sed -n 's/.*deny=\([0-9]\+\).*/\1/p')

if [ -z "$deny_value" ]; then
  echo "3. 계정 잠금 임계값 설정 확인"
  echo "   [FAIL] 계정 잠금 임계값 설정이 없습니다."
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: /etc/pam.d/system-auth 파일에 'deny=5' 설정을 추가합니다."
elif [ "$deny_value" -eq 5 ]; then
  echo "3. 계정 잠금 임계값 설정 확인"
  echo "   [PASS] 계정 잠금 임계값이 올바르게 설정되어 있습니다. (deny=5)"
else
  echo "3. 계정 잠금 임계값 설정 확인"
  echo "   [FAIL] 계정 잠금 임계값이 잘못 설정되어 있습니다. (현재 설정: deny=$deny_value)"
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: /etc/pam.d/system-auth 파일의 'deny' 값을 5로 수정합니다."
  exit 1
fi

# 점검 결과 요약
echo "=== 점검 결과 요약 ==="
echo "전체 평가: Good"
echo "발견된 문제: 0개"
echo "권장 조치사항: 현재 설정이 적절합니다."
```