# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_d33e8936-1d25-4acf-96ef-f79cc7507d75
# Generated: 2025-10-17T06:52:27.589Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-17-15h
# - Full Path: /2025-10-17-15h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === /etc/hosts 소유자·권한 점검 스크립트 ===
# 스크립트 ID: U-09
# 생성 시간: $(date)
# 설정값 요약: /etc/hosts 경로: /etc/hosts, 권한 허용값: 644, 허용 소유자:그룹: root:root

# 점검할 파일 경로
FILE="/etc/hosts"

# 권한 및 소유자 설정값
EXPECTED_PERMISSIONS="644"
EXPECTED_OWNER="root"
EXPECTED_GROUP="root"

# 점검 결과 변수 초기화
RESULTS=()
ISSUES=0

# 파일 존재 여부 점검
if [ ! -e "$FILE" ]; then
    echo "파일이 존재하지 않습니다: $FILE"
    RESULTS+=("1. 파일 존재 여부: [FAIL] $FILE가 존재하지 않습니다.")
    ISSUES=$((ISSUES + 1))
else
    # 파일 권한 점검
    PERMISSIONS=$(stat -c "%a" "$FILE")
    if [ "$PERMISSIONS" -ne "$EXPECTED_PERMISSIONS" ]; then
        RESULTS+=("1. 파일 권한 점검: [FAIL] 권한이 $EXPECTED_PERMISSIONS가 아닙니다. 현재 권한: $PERMISSIONS")
        ISSUES=$((ISSUES + 1))
    else
        RESULTS+=("1. 파일 권한 점검: [PASS] 권한이 $EXPECTED_PERMISSIONS입니다.")
    fi

    # 파일 소유자 점검
    OWNER=$(stat -c "%U" "$FILE")
    GROUP=$(stat -c "%G" "$FILE")
    if [ "$OWNER" != "$EXPECTED_OWNER" ] || [ "$GROUP" != "$EXPECTED_GROUP" ]; then
        RESULTS+=("2. 파일 소유자·그룹 점검: [FAIL] 소유자: $EXPECTED_OWNER, 그룹: $EXPECTED_GROUP가 아닙니다. 현재 소유자: $OWNER, 그룹: $GROUP")
        ISSUES=$((ISSUES + 1))
    else
        RESULTS+=("2. 파일 소유자·그룹 점검: [PASS] 소유자와 그룹이 올바릅니다.")
    fi
fi

# 점검 결과 출력
echo "=== /etc/hosts 소유자·권한 점검 결과 ==="
for result in "${RESULTS[@]}"; do
    echo "$result"
done

# 전체 점검 결과 요약
if [ $ISSUES -eq 0 ]; then
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Good"
    echo "발견된 문제: 0개"
    echo "권장 조치사항: 없음"
else
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: $ISSUES 개"
    echo "권장 조치사항: 파일 권한 및 소유자를 $EXPECTED_PERMISSIONS, $EXPECTED_OWNER:$EXPECTED_GROUP로 설정하세요."
fi
```