# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_50c1c2bc-0ff1-4273-845b-44badff8bc4f
# Generated: 2025-10-17T06:55:54.657Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-17-15h
# - Full Path: /2025-10-17-15h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === Root 계정 원격 접속 제한 점검 결과 ===
# 점검 시간: 현재 시간
# 설정 적용: SSH 설정 파일 경로, PAM 로그인 설정 파일 경로, securetty 파일 경로

echo "점검 시간: $(date)"
echo "설정 적용: SSH 설정 파일 경로: /etc/ssh/sshd_config, PAM 로그인 설정 파일 경로: /etc/pam.d/login, securetty 파일 경로: /etc/securetty"

# 초기 상태 변수 설정
status=0
issues=0
recommendations=""

# 1. SSH 설정 파일 점검
if [ -f /etc/ssh/sshd_config ]; then
    if grep -q "^PermitRootLogin no" /etc/ssh/sshd_config; then
        echo "1. SSH 설정: root 로그인 제한"
        echo "[PASS] root 계정의 SSH 접속이 제한되어 있습니다."
    else
        echo "1. SSH 설정: root 로그인 제한"
        echo "[FAIL] root 계정의 SSH 접속이 허용되어 있습니다."
        issues=$((issues + 1))
        recommendations+="SSH 설정 파일에서 'PermitRootLogin no'으로 변경하세요. "
    fi
else
    echo "1. SSH 설정: root 로그인 제한"
    echo "[FAIL] SSH 설정 파일이 존재하지 않습니다."
    issues=$((issues + 1))
    recommendations+="SSH 설정 파일이 필요합니다. "
fi

# 2. PAM 로그인 설정 점검
if [ -f /etc/pam.d/login ]; then
    if grep -q "auth required pam_securetty.so" /etc/pam.d/login; then
        echo "2. PAM 로그인 설정: root 로그인 제한"
        echo "[PASS] PAM 설정이 올바르게 구성되어 있습니다."
    else
        echo "2. PAM 로그인 설정: root 로그인 제한"
        echo "[FAIL] PAM 설정이 올바르지 않습니다."
        issues=$((issues + 1))
        recommendations+="PAM 설정 파일에 'auth required pam_securetty.so'를 추가하세요. "
    fi
else
    echo "2. PAM 로그인 설정: root 로그인 제한"
    echo "[FAIL] PAM 로그인 설정 파일이 존재하지 않습니다."
    issues=$((issues + 1))
    recommendations+="PAM 로그인 설정 파일이 필요합니다. "
fi

# 3. securetty 파일 점검
if [ -f /etc/securetty ]; then
    if grep -q "^tty[0-9]*$" /etc/securetty; then
        echo "3. securetty 파일: root 로그인 제한"
        echo "[PASS] securetty 파일이 올바르게 구성되어 있습니다."
    else
        echo "3. securetty 파일: root 로그인 제한"
        echo "[FAIL] securetty 파일이 올바르지 않습니다."
        issues=$((issues + 1))
        recommendations+="securetty 파일에 tty를 추가하세요. "
    fi
else
    echo "3. securetty 파일: root 로그인 제한"
    echo "[FAIL] securetty 파일이 존재하지 않습니다."
    issues=$((issues + 1))
    recommendations+="securetty 파일이 필요합니다. "
fi

# === 점검 결과 요약 ===
if [ $issues -eq 0 ]; then
    overall_status="Good"
else
    overall_status="Vulnerable"
fi

echo "=== 점검 결과 요약 ==="
echo "전체 평가: $overall_status"
echo "발견된 문제: $issues 개"
if [ $issues -gt 0 ]; then
    echo "권장 조치사항: $recommendations"
fi
```