# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_c0768475-5655-4ff4-95d7-896f1923aa2b
# Generated: 2025-10-12T13:02:22.628Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-12-22h
# - Full Path: /2025-10-12-22h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === /etc/shadow 소유자·권한 점검 스크립트 ===
# 스크립트 ID: U-08
# 생성 시간: $(date)
# 설정값 요약: 
# - 점검 파일: /etc/shadow
# - 허용 권한: 600, 640
# - 허용 소유자:그룹: root:root, root:shadow

# 점검할 파일 경로
SHADOW_FILE="/etc/shadow"

# 허용 권한 및 소유자/그룹 설정
ALLOWED_PERMISSIONS=("600" "640")
ALLOWED_OWNERS=("root:root" "root:shadow")

# 점검 결과 초기화
RESULTS=()
STATUS="Good"
ISSUE_COUNT=0

# 파일 존재 여부 점검
if [ ! -e "$SHADOW_FILE" ]; then
    echo "ERROR: $SHADOW_FILE 파일이 존재하지 않습니다."
    exit 1
fi

# 파일 권한 점검
PERMISSIONS=$(stat -c "%a" "$SHADOW_FILE")
if [[ " ${ALLOWED_PERMISSIONS[@]} " =~ " ${PERMISSIONS} " ]]; then
    RESULTS+=("1. 권한 점검: [PASS] 권한($PERMISSIONS) 허용값 내에 존재")
else
    RESULTS+=("1. 권한 점검: [FAIL] 권한($PERMISSIONS) 허용값($ALLOWED_PERMISSIONS) 외")
    STATUS="Vulnerable"
    ISSUE_COUNT=$((ISSUE_COUNT + 1))
fi

# 파일 소유자·그룹 점검
OWNER_GROUP=$(stat -c "%U:%G" "$SHADOW_FILE")
if [[ " ${ALLOWED_OWNERS[@]} " =~ " ${OWNER_GROUP} " ]]; then
    RESULTS+=("2. 소유자·그룹 점검: [PASS] 소유자·그룹($OWNER_GROUP) 허용값 내에 존재")
else
    RESULTS+=("2. 소유자·그룹 점검: [FAIL] 소유자·그룹($OWNER_GROUP) 허용값($ALLOWED_OWNERS) 외")
    STATUS="Vulnerable"
    ISSUE_COUNT=$((ISSUE_COUNT + 1))
fi

# === 점검 결과 출력 ===
echo "=== /etc/shadow 소유자·권한 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: [주요 설정값들 요약]"

for result in "${RESULTS[@]}"; do
    echo "$result"
done

# === 점검 결과 요약 ===
echo "=== 점검 결과 요약 ==="
echo "전체 평가: $STATUS"
echo "발견된 문제: $ISSUE_COUNT 개"
if [ "$ISSUE_COUNT" -gt 0 ]; then
    echo "권장 조치사항: 권한 및 소유자·그룹을 허용값으로 수정하세요."
fi
```