# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759285374273_84690y3fp
# Generated: 2025-10-01T02:22:54.910Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux.sh
# - Time-based Folder: 2025-10-01-11h
# - Full Path: /2025-10-01-11h/OS--Unknown--OSLinux.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash
# U-07: /etc/passwd 소유자·권한 점검 스크립트
# 생성 시간: $(date)
# 설정값 요약: /etc/passwd 경로=/etc/passwd, 권한 허용값=644, 허용 소유자:그룹=root:root

echo "=== /etc/passwd 소유자·권한 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: /etc/passwd 경로=/etc/passwd, 권한 허용값=644, 허용 소유자:그룹=root:root"

# /etc/passwd 파일 존재 여부 확인
if [ -f /etc/passwd ]; then
    # 파일 소유자 및 권한 확인
    OWNER=$(stat -c "%U:%G" /etc/passwd)
    PERM=$(stat -c "%a" /etc/passwd)
    
    echo "1. /etc/passwd 파일 정보:"
    echo "   소유자: $OWNER"
    echo "   권한: $PERM"
    
    # 소유자 점검
    if [ "$OWNER" = "root:root" ]; then
        echo "   [PASS] 소유자 설정이 적절합니다."
    else
        echo "   [FAIL] 소유자 설정을 검토해야 합니다."
    fi
    
    # 권한 점검
    if [ "$PERM" = "644" ]; then
        echo "   [PASS] 권한 설정이 적절합니다."
    else
        echo "   [FAIL] 권한 설정을 검토해야 합니다 (권장: 644)."
    fi
    
    # 파일 내용 기본 점검
    echo "2. 파일 내용 점검:"
    USER_COUNT=$(wc -l < /etc/passwd)
    echo "   등록된 사용자 수: $USER_COUNT"
    
    # UID 0 계정 점검
    ROOT_COUNT=$(awk -F: '$3==0' /etc/passwd | wc -l)
    echo "   UID 0 계정 수: $ROOT_COUNT"
    if [ "$ROOT_COUNT" -eq 1 ]; then
        echo "   [PASS] root 계정만 UID 0을 사용합니다."
    else
        echo "   [FAIL] 여러 계정이 UID 0을 사용합니다."
    fi
    
else
    echo "   [FAIL] /etc/passwd 파일이 존재하지 않습니다."
fi

echo "=== 점검 결과 요약 ==="
if [ "$OWNER" = "root:root" ] && [ "$PERM" = "644" ] && [ "$ROOT_COUNT" -eq 1 ]; then
    echo "전체 평가: Good"
    echo "발견된 문제: 0개"
    echo "권장 조치사항: 없음"
else
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개 이상"
    echo "권장 조치사항: /etc/passwd 파일의 소유자 및 권한 설정을 검토하고, UID 0 계정을 확인하세요."
fi
```