# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759284050881_ko01oty61
# Generated: 2025-10-01T02:00:51.898Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux.sh
# - Time-based Folder: 2025-10-01-11h
# - Full Path: /2025-10-01-11h/OS--Unknown--OSLinux.sh
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === 계정 잠금 임계값 설정 점검 스크립트 ===
# 스크립트 ID: U-03
# 카테고리: 계정관리
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# PAM system-auth 경로: /etc/pam.d/system-auth
# 실패 허용 횟수(deny): 5

# 점검 시간
echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: PAM 경로=/etc/pam.d/system-auth, 실패 허용 횟수=5"

# PAM 설정 파일 경로
PAM_FILE="/etc/pam.d/system-auth"
DENY_VALUE=5

# 파일 존재 여부 확인
if [ ! -f "$PAM_FILE" ]; then
    echo "1. PAM 설정 파일 존재 여부"
    echo "   [FAIL] $PAM_FILE 파일이 존재하지 않습니다."
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: $PAM_FILE 파일이 존재하는지 확인하고, 올바른 경로를 지정하세요."
    exit 1
fi

# 파일 읽기 권한 확인
if [ ! -r "$PAM_FILE" ]; then
    echo "1. PAM 설정 파일 읽기 권한"
    echo "   [FAIL] $PAM_FILE 파일에 읽기 권한이 없습니다."
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: 파일에 읽기 권한을 부여하세요."
    exit 1
fi

# 계정 잠금 임계값 설정 확인
LOCK_SETTING=$(grep -E "pam_tally2.so.*deny=$DENY_VALUE" "$PAM_FILE")

if [ -n "$LOCK_SETTING" ]; then
    echo "1. 계정 잠금 임계값 설정"
    echo "   [PASS] 계정 잠금 임계값이 올바르게 설정되어 있습니다."
else
    echo "1. 계정 잠금 임계값 설정"
    echo "   [FAIL] 계정 잠금 임계값이 올바르게 설정되어 있지 않습니다."
fi

# 점검 결과 요약
if [ -n "$LOCK_SETTING" ]; then
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Good"
    echo "발견된 문제: 0개"
    echo "권장 조치사항: 설정이 올바르게 적용되어 있습니다."
else
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: $PAM_FILE 파일에 'pam_tally2.so deny=$DENY_VALUE' 설정을 추가하세요."
fi
```