# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759293680356_lyxllu2yu
# Generated: 2025-10-01T04:41:21.022Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux.sh
# - Time-based Folder: 2025-10-01-13h
# - Full Path: /2025-10-01-13h/OS--Unknown--OSLinux.sh
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === Root 디렉토리 보안 설정 점검 스크립트 ===
# 스크립트 ID: U-05
# 카테고리: 파일보안
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# 설정값 요약: 허용 권한(700, 750), PATH 검사 활성화, 검사 파일(/root/.bashrc, /root/.profile)

# 점검 결과 저장 변수 초기화
result_summary=""
issue_count=0

# 점검 시간 출력
echo "=== Root 디렉토리 보안 설정 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: 허용 권한(700, 750), PATH 검사 활성화, 검사 파일(/root/.bashrc, /root/.profile)"
echo ""

# 1. Root 홈 디렉토리 권한 점검
echo "1. Root 홈 디렉토리 권한 점검"
root_dir_perm=$(stat -c "%a" /root 2>/dev/null)

if [[ $? -ne 0 ]]; then
    echo "   [FAIL] /root 디렉토리의 정보를 가져올 수 없습니다."
    result_summary+="Root 디렉토리 권한 점검 실패\n"
    ((issue_count++))
else
    if [[ "$root_dir_perm" == "700" || "$root_dir_perm" == "750" ]]; then
        echo "   [PASS] /root 디렉토리 권한이 적절합니다: $root_dir_perm"
    else
        echo "   [FAIL] /root 디렉토리 권한이 부적절합니다: $root_dir_perm"
        result_summary+="Root 디렉토리 권한 부적절: $root_dir_perm\n"
        ((issue_count++))
    fi
fi

# 2. PATH에서 현재 디렉토리(.) 검사
echo ""
echo "2. PATH에서 현재 디렉토리(.) 검사"
if echo "$PATH" | grep -q "::\|:/:\|^:\|:$\|:.\|^.\|:.:$"; then
    echo "   [FAIL] PATH에 현재 디렉토리(.)가 포함되어 있습니다."
    result_summary+="PATH에 현재 디렉토리(.) 포함\n"
    ((issue_count++))
else
    echo "   [PASS] PATH에 현재 디렉토리(.)가 포함되어 있지 않습니다."
fi

# 3. Shell 설정 파일 점검
echo ""
echo "3. Shell 설정 파일 점검"
for file in /root/.bashrc /root/.profile; do
    if [[ -f "$file" ]]; then
        if grep -q "::\|:/:\|^:\|:$\|:.\|^.\|:.:$" "$file"; then
            echo "   [FAIL] $file 에 PATH에 현재 디렉토리(.)가 포함되어 있습니다."
            result_summary+="$file 에 PATH에 현재 디렉토리(.) 포함\n"
            ((issue_count++))
        else
            echo "   [PASS] $file 에 PATH에 현재 디렉토리(.)가 포함되어 있지 않습니다."
        fi
    else
        echo "   [FAIL] $file 파일이 존재하지 않습니다."
        result_summary+="$file 파일 없음\n"
        ((issue_count++))
    fi
done

# === 점검 결과 요약 ===
echo ""
echo "=== 점검 결과 요약 ==="
if [[ $issue_count -eq 0 ]]; then
    echo "전체 평가: Good"
    echo "발견된 문제: 0개"
else
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: $issue_count 개"
    echo -e "권장 조치사항:\n$result_summary"
fi
```