# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759311864886_hfkqr6r5y
# Generated: 2025-10-01T09:44:25.582Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-01-18h
# - Full Path: /2025-10-01-18h/OS--Unknown--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === /etc/hosts 소유자·권한 점검 스크립트 ===
# 스크립트 ID: U-09
# 카테고리: 파일보안
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# 설정 적용: /etc/hosts 경로: /etc/hosts, 권한 허용값: 644, 허용 소유자:그룹: root:root

# 점검 시간
echo "=== /etc/hosts 소유자·권한 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: /etc/hosts 경로: /etc/hosts, 권한 허용값: 644, 허용 소유자:그룹: root:root"
echo ""

# 점검 항목 1: 파일 존재 여부 확인
if [ ! -e /etc/hosts ]; then
    echo "1. /etc/hosts 파일 존재 여부"
    echo "   [FAIL] /etc/hosts 파일이 존재하지 않습니다."
    echo ""
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: /etc/hosts 파일을 생성하고 적절한 내용을 추가하세요."
    exit 1
fi

# 점검 항목 2: 파일 소유자 및 그룹 확인
owner_group=$(stat -c "%U:%G" /etc/hosts)
if [ "$owner_group" != "root:root" ]; then
    echo "2. /etc/hosts 소유자 및 그룹 확인"
    echo "   [FAIL] 현재 소유자:그룹은 $owner_group 입니다. (허용: root:root)"
else
    echo "2. /etc/hosts 소유자 및 그룹 확인"
    echo "   [PASS] 소유자:그룹이 올바르게 설정되어 있습니다."
fi

# 점검 항목 3: 파일 권한 확인
permissions=$(stat -c "%a" /etc/hosts)
if [ "$permissions" != "644" ]; then
    echo "3. /etc/hosts 파일 권한 확인"
    echo "   [FAIL] 현재 권한은 $permissions 입니다. (허용: 644)"
else
    echo "3. /etc/hosts 파일 권한 확인"
    echo "   [PASS] 파일 권한이 올바르게 설정되어 있습니다."
fi

# 점검 결과 요약
echo ""
echo "=== 점검 결과 요약 ==="
if [ "$owner_group" == "root:root" ] && [ "$permissions" == "644" ]; then
    echo "전체 평가: Good"
    echo "발견된 문제: 0개"
    echo "권장 조치사항: 없음"
else
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개 이상"
    echo "권장 조치사항: /etc/hosts 파일의 소유자:그룹을 root:root로, 권한을 644로 설정하세요."
fi
```