# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: force_957a4a46-3cbe-46cf-a41e-7250b2e80839
# Generated: 2025-10-12T12:54:24.276Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: Script Completion Forcer
#
# File Information:
# - File Name: OS--Unknown--OSLinux.sh
# - Time-based Folder: 2025-10-12-21h
# - Full Path: /2025-10-12-21h/OS--Unknown--OSLinux.sh
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === /etc/passwd 소유자·권한 점검 스크립트 ===
# 생성 시간: $(date)
# 설정값 요약: 권한 허용값 644, 소유자:그룹 root:root

# 점검할 파일 경로
FILE="/etc/passwd"
# 허용 권한
ALLOWED_PERMISSIONS="644"
# 허용 소유자:그룹
ALLOWED_OWNER="root:root"

# 파일 존재 여부 점검
if [ ! -e "$FILE" ]; then
    echo "=== 점검 결과 ==="
    echo "점검 시간: $(date)"
    echo "설정 적용: [파일 존재 여부 점검]"
    echo "1. /etc/passwd 파일 존재 여부"
    echo "[FAIL] /etc/passwd 파일이 존재하지 않습니다."
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: /etc/passwd 파일을 생성하거나 복구하십시오."
    exit 1
fi

# 파일 권한 점검
CURRENT_PERMISSIONS=$(stat -c "%a" "$FILE")
if [ "$CURRENT_PERMISSIONS" -ne "$ALLOWED_PERMISSIONS" ]; then
    PERMISSION_STATUS="[FAIL] 현재 권한: $CURRENT_PERMISSIONS, 허용 권한: $ALLOWED_PERMISSIONS"
else
    PERMISSION_STATUS="[PASS] 현재 권한: $CURRENT_PERMISSIONS, 허용 권한: $ALLOWED_PERMISSIONS"
fi

# 파일 소유자 및 그룹 점검
CURRENT_OWNER=$(stat -c "%U:%G" "$FILE")
if [ "$CURRENT_OWNER" != "$ALLOWED_OWNER" ]; then
    OWNER_STATUS="[FAIL] 현재 소유자: $CURRENT_OWNER, 허용 소유자: $ALLOWED_OWNER"
else
    OWNER_STATUS="[PASS] 현재 소유자: $CURRENT_OWNER, 허용 소유자: $ALLOWED_OWNER"
fi

# 점검 결과 출력
echo "=== 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: [주요 설정값들 요약]"
echo "1. /etc/passwd 파일 존재 여부"
echo "$PERMISSION_STATUS"
echo "2. /etc/passwd 파일 소유자 및 그룹"
echo "$OWNER_STATUS"

# 전체 평가 및 요약
if [[ "$PERMISSION_STATUS" == *"[FAIL]"* || "$OWNER_STATUS" == *"[FAIL]"* ]]; then
    OVERALL_STATUS="Vulnerable"
    ISSUE_COUNT=2
    if [[ "$PERMISSION_STATUS" == *"[PASS]"* ]]; then
        ISSUE_COUNT=1
    fi
else
    OVERALL_STATUS="Good"
    ISSUE_COUNT=0
fi

echo "=== 점검 결과 요약 ==="
echo "전체 평가: $OVERALL_STATUS"
echo "발견된 문제: $ISSUE_COUNT 개"
if [ "$OVERALL_STATUS" == "Vulnerable" ]; then
    echo "권장 조치사항: /etc/passwd 파일의 권한 및 소유자를 확인하고 수정하십시오."
fi
```