# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_7a1c60d7-dbd5-4287-9631-c046fcdaa4fe
# Generated: 2025-10-12T12:48:28.118Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-12-21h
# - Full Path: /2025-10-12-21h/OS--Unknown--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === Root 디렉토리 보안 설정 점검 스크립트 ===
# 스크립트 ID: U-05
# 생성 시간: $(date)
# 설정값 요약: 허용 가능한 Root 홈 디렉토리 권한: 700, 750
# PATH에서 현재 디렉토리(.) 검사: 활성화
# 검사할 Shell 설정 파일: /root/.bashrc, /root/.profile

# 점검 결과 변수 초기화
result=0
issues=0
report=""

# 함수: 점검 결과 추가
add_to_report() {
    report+="$1\n"
}

# 1. Root 홈 디렉토리 권한 점검
root_home_perm=$(stat -c "%a" /root)
if [[ "$root_home_perm" == "700" || "$root_home_perm" == "750" ]]; then
    add_to_report "1. Root 홈 디렉토리 권한: $root_home_perm [PASS]"
else
    add_to_report "1. Root 홈 디렉토리 권한: $root_home_perm [FAIL]"
    issues=$((issues + 1))
    result=1
fi

# 2. 현재 디렉토리(.) PATH 포함 여부 점검
if echo "$PATH" | grep -q "\."; then
    add_to_report "2. 현재 디렉토리(.) PATH 포함: [FAIL]"
    issues=$((issues + 1))
    result=1
else
    add_to_report "2. 현재 디렉토리(.) PATH 포함: [PASS]"
fi

# 3. Shell 설정 파일 점검
for file in /root/.bashrc /root/.profile; do
    if [[ -e "$file" ]]; then
        file_perm=$(stat -c "%a" "$file")
        if [[ "$file_perm" == "600" || "$file_perm" == "644" ]]; then
            add_to_report "3. $file 권한: $file_perm [PASS]"
        else
            add_to_report "3. $file 권한: $file_perm [FAIL]"
            issues=$((issues + 1))
            result=1
        fi
    else
        add_to_report "3. $file 존재하지 않음 [FAIL]"
        issues=$((issues + 1))
        result=1
    fi
done

# === 점검 결과 출력 ===
echo -e "=== Root 디렉토리 보안 설정 점검 결과 ==="
echo -e "점검 시간: $(date)"
echo -e "설정 적용: [허용 가능한 Root 홈 디렉토리 권한: 700, 750]"

# 점검 결과 리포트 출력
echo -e "$report"

# === 점검 결과 요약 ===
if [[ $result -eq 0 ]]; then
    echo -e "전체 평가: Good"
else
    echo -e "전체 평가: Vulnerable"
fi
echo -e "발견된 문제: $issues 개"
echo -e "권장 조치사항: Root 홈 디렉토리 권한을 700 또는 750으로 설정하고, 현재 디렉토리를 PATH에서 제거하세요."
```