# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759298198435_tc7eb0ugi
# Generated: 2025-10-01T05:56:39.273Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-01-14h
# - Full Path: /2025-10-01-14h/OS--Unknown--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 패스워드 파일 보호 점검 스크립트 ===
# 스크립트 ID: U-04
# 카테고리: 파일보안
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# 설정값 요약:
#   /etc/passwd 경로: /etc/passwd
#   /etc/shadow 경로: /etc/shadow
#   passwd 권한 허용값: 644
#   shadow 권한 허용값: 600, 640

# 점검 시간
echo "=== 패스워드 파일 보호 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: /etc/passwd 권한 644, /etc/shadow 권한 600 또는 640"

# 점검 결과 변수 초기화
overall_status="Good"
issues_found=0

# /etc/passwd 파일 권한 점검
echo ""
echo "1. /etc/passwd 파일 권한 점검"
if [ -e /etc/passwd ]; then
    passwd_perm=$(stat -c "%a" /etc/passwd)
    if [ "$passwd_perm" -eq 644 ]; then
        echo "   [PASS] /etc/passwd 파일의 권한이 644로 설정되어 있습니다."
    else
        echo "   [FAIL] /etc/passwd 파일의 권한이 $passwd_perm로 설정되어 있습니다. (권장: 644)"
        overall_status="Vulnerable"
        issues_found=$((issues_found + 1))
    fi
else
    echo "   [FAIL] /etc/passwd 파일이 존재하지 않습니다."
    overall_status="Vulnerable"
    issues_found=$((issues_found + 1))
fi

# /etc/shadow 파일 권한 점검
echo ""
echo "2. /etc/shadow 파일 권한 점검"
if [ -e /etc/shadow ]; then
    shadow_perm=$(stat -c "%a" /etc/shadow)
    if [ "$shadow_perm" -eq 600 ] || [ "$shadow_perm" -eq 640 ]; then
        echo "   [PASS] /etc/shadow 파일의 권한이 $shadow_perm로 설정되어 있습니다."
    else
        echo "   [FAIL] /etc/shadow 파일의 권한이 $shadow_perm로 설정되어 있습니다. (권장: 600 또는 640)"
        overall_status="Vulnerable"
        issues_found=$((issues_found + 1))
    fi
else
    echo "   [FAIL] /etc/shadow 파일이 존재하지 않습니다."
    overall_status="Vulnerable"
    issues_found=$((issues_found + 1))
fi

# 점검 결과 요약
echo ""
echo "=== 점검 결과 요약 ==="
echo "전체 평가: $overall_status"
echo "발견된 문제: $issues_found 개"
if [ "$overall_status" == "Vulnerable" ]; then
    echo "권장 조치사항: /etc/passwd 파일의 권한을 644로, /etc/shadow 파일의 권한을 600 또는 640으로 설정하세요."
else
    echo "모든 설정이 올바르게 구성되어 있습니다."
fi
```