# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_1ea39b91-9818-4c5d-823c-44c641321d3e
# Generated: 2025-10-13T04:27:36.380Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-13-13h
# - Full Path: /2025-10-13-13h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 계정 잠금 임계값 설정 점검 스크립트 ===
# 스크립트 정보: U-03
# 생성 시간: $(date)
# 설정값 요약: PAM system-auth 경로: /etc/pam.d/system-auth, 실패 허용 횟수: 5

# 설정 파일 경로
PAM_FILE="/etc/pam.d/system-auth"
DENY_COUNT=5

# 점검 결과 변수 초기화
RESULT="PASS"
ISSUES=0
RECOMMENDATIONS=""

# 설정 파일 존재 여부 확인
if [ ! -f "$PAM_FILE" ]; then
    echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
    echo "점검 시간: $(date)"
    echo "설정 적용: PAM system-auth 파일이 존재하지 않습니다."
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: PAM system-auth 파일을 확인하세요."
    exit 1
fi

# 실패 허용 횟수 점검
if ! grep -q "deny=$DENY_COUNT" "$PAM_FILE"; then
    RESULT="FAIL"
    ISSUES=$((ISSUES + 1))
    RECOMMENDATIONS+="실패 허용 횟수를 $DENY_COUNT 로 설정하세요. "
fi

# 점검 결과 출력
echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: PAM system-auth 경로: $PAM_FILE, 실패 허용 횟수: $DENY_COUNT"

# 점검 항목 결과 출력
echo "1. 실패 허용 횟수 점검"
if [ "$RESULT" == "PASS" ]; then
    echo "   [PASS] 설정이 올바르게 적용되었습니다."
else
    echo "   [FAIL] 설정이 올바르게 적용되지 않았습니다."
fi

# 전체 점검 결과 요약
echo "=== 점검 결과 요약 ==="
if [ "$RESULT" == "PASS" ]; then
    echo "전체 평가: Good"
else
    echo "전체 평가: Vulnerable"
fi
echo "발견된 문제: $ISSUES 개"
if [ -n "$RECOMMENDATIONS" ]; then
    echo "권장 조치사항: $RECOMMENDATIONS"
fi
```