# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_0c66dbbf-be64-40f7-af9c-e89d6e1405c7
# Generated: 2025-10-13T04:23:59.808Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-13-13h
# - Full Path: /2025-10-13-13h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 패스워드 복잡성 정책 설정 점검 스크립트 ===
# 스크립트 ID: U-02
# 생성 시간: $(date)
# 설정값 요약:
# PAM system-auth 경로: /etc/pam.d/system-auth
# pwquality.conf 경로: /etc/security/pwquality.conf
# 최소 길이 요구사항: 8
# Linux 배포판: debian

# 점검 결과 초기화
result=0
issues=0
recommendations=""

# PAM system-auth 파일 존재 여부 점검
if [ ! -f /etc/pam.d/system-auth ]; then
    echo "1. PAM system-auth 파일이 존재하지 않습니다."
    echo "   [FAIL] PAM 설정 파일을 확인하세요."
    issues=$((issues + 1))
    recommendations+="PAM system-auth 파일을 생성하거나 복구하십시오.\n"
else
    # 최소 길이 요구사항 점검
    if grep -q "minlen=8" /etc/security/pwquality.conf; then
        echo "1. 최소 패스워드 길이 요구사항이 설정되어 있습니다."
        echo "   [PASS] 최소 길이: 8"
    else
        echo "1. 최소 패스워드 길이 요구사항이 설정되어 있지 않습니다."
        echo "   [FAIL] 최소 길이: 8"
        issues=$((issues + 1))
        recommendations+="pwquality.conf 파일에서 minlen=8을 설정하십시오.\n"
    fi
fi

# pwquality.conf 파일 존재 여부 점검
if [ ! -f /etc/security/pwquality.conf ]; then
    echo "2. pwquality.conf 파일이 존재하지 않습니다."
    echo "   [FAIL] pwquality 설정 파일을 확인하세요."
    issues=$((issues + 1))
    recommendations+="pwquality.conf 파일을 생성하거나 복구하십시오.\n"
else
    # pwquality.conf 파일에서 최소 길이 점검
    if grep -q "^minlen=8" /etc/security/pwquality.conf; then
        echo "2. pwquality.conf에서 최소 패스워드 길이 요구사항이 설정되어 있습니다."
        echo "   [PASS] 최소 길이: 8"
    else
        echo "2. pwquality.conf에서 최소 패스워드 길이 요구사항이 설정되어 있지 않습니다."
        echo "   [FAIL] 최소 길이: 8"
        issues=$((issues + 1))
        recommendations+="pwquality.conf 파일에서 minlen=8을 설정하십시오.\n"
    fi
fi

# 점검 결과 요약 출력
echo "=== 점검 결과 요약 ==="
if [ $issues -eq 0 ]; then
    echo "전체 평가: Good"
    echo "발견된 문제: 0개"
else
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: $issues 개"
    echo -e "권장 조치사항:\n$recommendations"
fi
```