# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_712bc927-5cf7-4d4c-9b83-c15079e8cec8
# Generated: 2025-10-10T04:31:11.179Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-10-13h
# - Full Path: /2025-10-10-13h/OS--Unknown--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 패스워드 파일 보호 점검 스크립트 ===
# 스크립트 ID: U-04
# 생성 시간: $(date)
# 설정값 요약:
# - /etc/passwd 경로: /etc/passwd
# - /etc/shadow 경로: /etc/shadow
# - passwd 권한 허용값: 644
# - shadow 권한 허용값: 600, 640

# 점검 시간
echo "=== 패스워드 파일 보호 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: /etc/passwd 권한 644, /etc/shadow 권한 600 또는 640"

# /etc/passwd 파일 점검
echo ""
echo "1. /etc/passwd 파일 권한 점검"
if [ ! -e /etc/passwd ]; then
  echo "   [FAIL] /etc/passwd 파일이 존재하지 않습니다."
elif [ ! -r /etc/passwd ]; then
  echo "   [FAIL] /etc/passwd 파일을 읽을 수 있는 권한이 없습니다."
else
  passwd_perm=$(stat -c "%a" /etc/passwd)
  if [ "$passwd_perm" -eq 644 ]; then
    echo "   [PASS] /etc/passwd 파일 권한이 적절합니다. ($passwd_perm)"
  else
    echo "   [FAIL] /etc/passwd 파일 권한이 부적절합니다. ($passwd_perm)"
  fi
fi

# /etc/shadow 파일 점검
echo ""
echo "2. /etc/shadow 파일 권한 점검"
if [ ! -e /etc/shadow ]; then
  echo "   [FAIL] /etc/shadow 파일이 존재하지 않습니다."
elif [ ! -r /etc/shadow ]; then
  echo "   [FAIL] /etc/shadow 파일을 읽을 수 있는 권한이 없습니다."
else
  shadow_perm=$(stat -c "%a" /etc/shadow)
  if [ "$shadow_perm" -eq 600 ] || [ "$shadow_perm" -eq 640 ]; then
    echo "   [PASS] /etc/shadow 파일 권한이 적절합니다. ($shadow_perm)"
  else
    echo "   [FAIL] /etc/shadow 파일 권한이 부적절합니다. ($shadow_perm)"
  fi
fi

# 점검 결과 요약
echo ""
echo "=== 점검 결과 요약 ==="
fail_count=$(grep -c "\[FAIL\]" <(echo "$output"))
if [ "$fail_count" -eq 0 ]; then
  echo "전체 평가: Good"
  echo "발견된 문제: 0개"
  echo "권장 조치사항: 모든 파일 권한이 적절합니다."
else
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: $fail_count 개"
  echo "권장 조치사항: 위의 FAIL 항목에 대해 권한을 적절히 수정하세요."
fi
```