# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_db33b199-33af-40e8-afe6-4be8903a42ca
# Generated: 2025-10-10T04:16:56.528Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-10-13h
# - Full Path: /2025-10-10-13h/OS--Unknown--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === /etc/shadow 소유자·권한 점검 스크립트 ===
# 스크립트 ID: U-08
# 카테고리: 파일보안
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# 설정 적용: /etc/shadow 경로=/etc/shadow, 권한 허용값=600, 640, 허용 소유자:그룹=root:root, root:shadow

# 점검 시간 기록
echo "=== /etc/shadow 소유자·권한 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: /etc/shadow 경로=/etc/shadow, 권한 허용값=600, 640, 허용 소유자:그룹=root:root, root:shadow"
echo ""

# /etc/shadow 파일 존재 여부 확인
if [ ! -e /etc/shadow ]; then
  echo "1. /etc/shadow 파일 존재 여부"
  echo "   [FAIL] /etc/shadow 파일이 존재하지 않습니다."
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: /etc/shadow 파일이 존재하는지 확인하고, 시스템 설정을 점검하세요."
  exit 1
fi

# /etc/shadow 파일의 소유자 및 그룹 확인
owner_group=$(stat -c "%U:%G" /etc/shadow)
if [[ "$owner_group" == "root:root" || "$owner_group" == "root:shadow" ]]; then
  echo "1. /etc/shadow 파일 소유자 및 그룹 확인"
  echo "   [PASS] 소유자 및 그룹이 적절합니다: $owner_group"
else
  echo "1. /etc/shadow 파일 소유자 및 그룹 확인"
  echo "   [FAIL] 소유자 및 그룹이 부적절합니다: $owner_group"
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: /etc/shadow 파일의 소유자 및 그룹을 root:root 또는 root:shadow로 설정하세요."
  exit 1
fi

# /etc/shadow 파일의 권한 확인
permissions=$(stat -c "%a" /etc/shadow)
if [[ "$permissions" == "600" || "$permissions" == "640" ]]; then
  echo "2. /etc/shadow 파일 권한 확인"
  echo "   [PASS] 권한이 적절합니다: $permissions"
else
  echo "2. /etc/shadow 파일 권한 확인"
  echo "   [FAIL] 권한이 부적절합니다: $permissions"
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: /etc/shadow 파일의 권한을 600 또는 640으로 설정하세요."
  exit 1
fi

# 모든 점검 항목 통과
echo "=== 점검 결과 요약 ==="
echo "전체 평가: Good"
echo "발견된 문제: 0개"
echo "권장 조치사항: 모든 설정이 적절합니다."
```