# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_f177d539-9255-4c76-a5ef-b76e6ee21973
# Generated: 2025-10-13T06:06:05.532Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-13-15h
# - Full Path: /2025-10-13-15h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 파일/디렉터리 소유자 설정 점검 결과 ===
# 점검 시간: 현재 시간
# 설정 적용: 소유자 변경 대상 파일 및 디렉터리

# 설정값 요약
TARGET_FILES=("/etc/passwd" "/etc/shadow" "/etc/group")
ALLOWED_OWNER="root:root"
DISTRO_CHECK=$(cat /etc/os-release | grep '^ID=' | cut -d'=' -f2)

# 점검 결과 변수 초기화
RESULTS=()
ISSUE_COUNT=0

# RHEL 배포판 확인
if [[ "$DISTRO_CHECK" != "rhel" ]]; then
    echo "현재 사용 중인 리눅스 배포판은 RHEL이 아닙니다. 점검을 중단합니다."
    exit 1
fi

# 파일 소유자 변경 및 권한 확인
for FILE in "${TARGET_FILES[@]}"; do
    echo "점검 중: $FILE"
    
    # 파일 존재 여부 확인
    if [[ ! -e "$FILE" ]]; then
        echo "$FILE: [FAIL] 파일이 존재하지 않습니다."
        RESULTS+=("$FILE: [FAIL] 파일이 존재하지 않습니다.")
        ISSUE_COUNT=$((ISSUE_COUNT + 1))
        continue
    fi

    # 현재 소유자 확인
    CURRENT_OWNER=$(ls -l "$FILE" | awk '{print $3":"$4}')
    
    # 소유자 변경 시도 (실제 변경은 하지 않음)
    if [[ "$CURRENT_OWNER" != "$ALLOWED_OWNER" ]]; then
        echo "$FILE: [FAIL] 현재 소유자 ($CURRENT_OWNER)와 허용 소유자 ($ALLOWED_OWNER)가 다릅니다."
        RESULTS+=("$FILE: [FAIL] 현재 소유자 ($CURRENT_OWNER)와 허용 소유자 ($ALLOWED_OWNER)가 다릅니다.")
        ISSUE_COUNT=$((ISSUE_COUNT + 1))
    else
        echo "$FILE: [PASS] 소유자가 올바르게 설정되어 있습니다."
        RESULTS+=("$FILE: [PASS] 소유자가 올바르게 설정되어 있습니다.")
    fi
done

# === 점검 결과 요약 ===
echo "=== 점검 결과 요약 ==="
if [[ $ISSUE_COUNT -eq 0 ]]; then
    echo "전체 평가: Good"
    echo "발견된 문제: 0개"
else
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: $ISSUE_COUNT 개"
fi

# 점검 결과 출력
for RESULT in "${RESULTS[@]}"; do
    echo "$RESULT"
done
```