# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: 47824ead-9e2c-4b8f-b510-fda2dd89bebf_1760060578954
# Generated: 2025-10-10T01:43:00.838Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-10-10h
# - Full Path: /2025-10-10-10h/OS--Unknown--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 계정 잠금 임계값 설정 점검 스크립트 ===
# 스크립트 ID: U-03
# 카테고리: 계정관리
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# PAM system-auth 경로: /etc/pam.d/system-auth
# 실패 허용 횟수(deny): 5

# 점검 시간
echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: PAM 경로=/etc/pam.d/system-auth, 실패 허용 횟수=5"

# PAM 설정 파일 경로
PAM_FILE="/etc/pam.d/system-auth"
DENY_VALUE=5

# 파일 존재 여부 및 읽기 권한 확인
if [ ! -f "$PAM_FILE" ]; then
    echo "1. PAM 설정 파일 존재 여부"
    echo "   [FAIL] $PAM_FILE 파일이 존재하지 않습니다."
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: $PAM_FILE 파일이 존재하는지 확인하고, 올바른 경로를 설정하세요."
    exit 1
fi

if [ ! -r "$PAM_FILE" ]; then
    echo "1. PAM 설정 파일 읽기 권한"
    echo "   [FAIL] $PAM_FILE 파일에 대한 읽기 권한이 없습니다."
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: 파일에 대한 읽기 권한을 확인하고, 필요한 경우 권한을 조정하세요."
    exit 1
fi

# 설정 파일에서 deny 값 확인
deny_setting=$(grep -E "pam_tally2.so.*deny=" "$PAM_FILE" | grep -o "deny=[0-9]*" | cut -d= -f2)

if [ -z "$deny_setting" ]; then
    echo "2. 계정 잠금 임계값 설정 확인"
    echo "   [FAIL] $PAM_FILE 파일에 'deny' 설정이 없습니다."
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: 'deny=$DENY_VALUE' 설정을 추가하여 계정 잠금 임계값을 설정하세요."
    exit 1
fi

if [ "$deny_setting" -eq "$DENY_VALUE" ]; then
    echo "2. 계정 잠금 임계값 설정 확인"
    echo "   [PASS] 'deny' 설정이 올바르게 구성되어 있습니다. (현재 설정: $deny_setting)"
else
    echo "2. 계정 잠금 임계값 설정 확인"
    echo "   [FAIL] 'deny' 설정이 올바르지 않습니다. (현재 설정: $deny_setting, 기대 설정: $DENY_VALUE)"
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: 'deny=$DENY_VALUE'로 설정을 수정하세요."
    exit 1
fi

# 최종 결과 요약
echo "=== 점검 결과 요약 ==="
echo "전체 평가: Good"
echo "발견된 문제: 0개"
echo "권장 조치사항: 설정이 올바르게 구성되어 있습니다."
```