# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: 2cb60e2c-77d6-438a-b31f-a6c41d70f469_1760060381603
# Generated: 2025-10-10T01:39:42.364Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-10-10h
# - Full Path: /2025-10-10-10h/OS--Unknown--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 패스워드 복잡성 정책 설정 점검 스크립트 ===
# 스크립트 ID: U-02
# 카테고리: 패스워드정책
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# 사용자 설정 요약:
# - PAM system-auth 경로: /etc/pam.d/system-auth
# - pwquality.conf 경로: /etc/security/pwquality.conf
# - 최소 길이 요구사항: 8
# - Linux 배포판: auto

# 점검 시작 시간
echo "=== 패스워드 복잡성 정책 설정 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: PAM system-auth 경로: /etc/pam.d/system-auth, pwquality.conf 경로: /etc/security/pwquality.conf, 최소 길이 요구사항: 8"

# 점검 항목 1: /etc/pam.d/system-auth 파일 존재 및 읽기 권한 확인
echo ""
echo "1. /etc/pam.d/system-auth 파일 존재 및 읽기 권한 확인"
if [ -r /etc/pam.d/system-auth ]; then
    echo "   [PASS] /etc/pam.d/system-auth 파일이 존재하며 읽기 가능합니다."
else
    echo "   [FAIL] /etc/pam.d/system-auth 파일이 존재하지 않거나 읽기 권한이 없습니다."
fi

# 점검 항목 2: /etc/security/pwquality.conf 파일 존재 및 읽기 권한 확인
echo ""
echo "2. /etc/security/pwquality.conf 파일 존재 및 읽기 권한 확인"
if [ -r /etc/security/pwquality.conf ]; then
    echo "   [PASS] /etc/security/pwquality.conf 파일이 존재하며 읽기 가능합니다."
else
    echo "   [FAIL] /etc/security/pwquality.conf 파일이 존재하지 않거나 읽기 권한이 없습니다."
fi

# 점검 항목 3: 패스워드 최소 길이 설정 확인
echo ""
echo "3. 패스워드 최소 길이 설정 확인"
if grep -q "^minlen\s*=\s*8" /etc/security/pwquality.conf; then
    echo "   [PASS] 패스워드 최소 길이가 8로 설정되어 있습니다."
else
    echo "   [FAIL] 패스워드 최소 길이가 8로 설정되어 있지 않습니다."
fi

# 점검 결과 요약
echo ""
echo "=== 점검 결과 요약 ==="
fail_count=$(grep -c "\[FAIL\]" <<< "$(echo "$output")")
if [ "$fail_count" -eq 0 ]; then
    echo "전체 평가: Good"
    echo "발견된 문제: 0개"
    echo "권장 조치사항: 모든 설정이 올바르게 구성되어 있습니다."
else
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: $fail_count개"
    echo "권장 조치사항: 위의 FAIL 항목을 확인하고 설정을 수정하세요."
fi
```