# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: manual_5e7edf35-5c02-4b63-8717-295a5dbd4a23_1760075044084
# Generated: 2025-10-10T05:44:04.486Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: os
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--os--OSLinux.sh
# - Time-based Folder: 2025-10-10-14h
# - Full Path: /2025-10-10-14h/OS--os--OSLinux.sh
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === 패스워드 파일 보호 점검 스크립트 ===
# 스크립트 ID: U-04
# 카테고리: 파일보안
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# 설정값 요약:
# - /etc/passwd 경로: /etc/passwd
# - /etc/shadow 경로: /etc/shadow
# - passwd 권한 허용값: 644
# - shadow 권한 허용값: 600, 640

# 점검 시간
echo "=== 패스워드 파일 보호 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: /etc/passwd 권한 644, /etc/shadow 권한 600 또는 640"

# 점검 함수 정의
check_file_permission() {
    local file_path=$1
    local expected_perms=$2
    local file_name=$(basename "$file_path")

    # 파일 존재 여부 확인
    if [ ! -e "$file_path" ]; then
        echo "$file_name: FAIL - 파일이 존재하지 않습니다."
        return 1
    fi

    # 파일 권한 확인
    local actual_perms
    actual_perms=$(stat -c "%a" "$file_path")

    if [[ " $expected_perms " =~ " $actual_perms " ]]; then
        echo "$file_name: PASS - 권한이 적절합니다. ($actual_perms)"
    else
        echo "$file_name: FAIL - 권한이 적절하지 않습니다. (현재: $actual_perms, 허용: $expected_perms)"
    fi
}

# /etc/passwd 파일 점검
check_file_permission "/etc/passwd" "644"

# /etc/shadow 파일 점검
check_file_permission "/etc/shadow" "600 640"

# 요약 섹션
echo "=== 점검 결과 요약 ==="
fail_count=$(grep -c "FAIL" <<< "$(check_file_permission "/etc/passwd" "644"; check_file_permission "/etc/shadow" "600 640")")
if [ "$fail_count" -eq 0 ]; then
    echo "전체 평가: Good"
    echo "발견된 문제: 0개"
    echo "권장 조치사항: 없음"
else
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: $fail_count개"
    echo "권장 조치사항: 파일 권한을 적절히 설정하십시오."
fi
```