# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: manual_ee74a59e-40d4-4327-b3cd-b19c8677ab98_1760074856293
# Generated: 2025-10-10T05:40:58.169Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: os
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--os--OSLinux.sh
# - Time-based Folder: 2025-10-10-14h
# - Full Path: /2025-10-10-14h/OS--os--OSLinux.sh
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === 계정 잠금 임계값 설정 점검 스크립트 ===
# 스크립트 ID: U-03
# 카테고리: 계정관리
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# PAM system-auth 경로: /etc/pam.d/system-auth
# 실패 허용 횟수(deny): 5
# Linux 배포판: auto

# === 점검 로직 ===

# PAM 설정 파일 경로
PAM_FILE="/etc/pam.d/system-auth"
# 실패 허용 횟수 설정
DENY_VALUE=5

# 파일 존재 여부 확인
if [ ! -f "$PAM_FILE" ]; then
  echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
  echo "점검 시간: $(date)"
  echo "설정 적용: PAM 설정 파일이 존재하지 않습니다."
  echo "1. PAM 설정 파일 확인"
  echo "   [FAIL] $PAM_FILE 파일이 존재하지 않습니다."
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: PAM 설정 파일의 경로를 확인하고, 파일이 존재하는지 확인하세요."
  exit 1
fi

# 파일 읽기 권한 확인
if [ ! -r "$PAM_FILE" ]; then
  echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
  echo "점검 시간: $(date)"
  echo "설정 적용: PAM 설정 파일을 읽을 수 없습니다."
  echo "1. PAM 설정 파일 권한 확인"
  echo "   [FAIL] $PAM_FILE 파일을 읽을 수 있는 권한이 없습니다."
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: 파일 읽기 권한을 확인하고, 필요한 경우 권한을 조정하세요."
  exit 1
fi

# 설정 파일에서 deny 값 확인
DENY_SETTING=$(grep -E "pam_tally2.so.*deny=$DENY_VALUE" "$PAM_FILE")

# deny 설정 확인
if [ -n "$DENY_SETTING" ]; then
  echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
  echo "점검 시간: $(date)"
  echo "설정 적용: 실패 허용 횟수 설정이 올바르게 적용되었습니다."
  echo "1. 실패 허용 횟수 설정 확인"
  echo "   [PASS] 실패 허용 횟수가 $DENY_VALUE로 설정되어 있습니다."
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Good"
  echo "발견된 문제: 0개"
  echo "권장 조치사항: 현재 설정을 유지하세요."
else
  echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
  echo "점검 시간: $(date)"
  echo "설정 적용: 실패 허용 횟수 설정이 올바르지 않습니다."
  echo "1. 실패 허용 횟수 설정 확인"
  echo "   [FAIL] 실패 허용 횟수가 $DENY_VALUE로 설정되어 있지 않습니다."
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: $PAM_FILE 파일에서 'pam_tally2.so' 모듈의 'deny' 값을 $DENY_VALUE로 설정하세요."
fi
```