# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: force_14658846-8c27-40d7-8be2-b7e2e118dc4f
# Generated: 2025-10-10T05:17:54.929Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: Script Completion Forcer
#
# File Information:
# - File Name: OS--Unknown--OSLinux.sh
# - Time-based Folder: 2025-10-10-14h
# - Full Path: /2025-10-10-14h/OS--Unknown--OSLinux.sh
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === /etc/passwd 소유자·권한 점검 스크립트 ===
# 스크립트 ID: U-07
# 카테고리: 파일보안
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# 설정 적용: /etc/passwd 경로=/etc/passwd, 권한 허용값=644, 허용 소유자:그룹=root:root

# 점검 시간
echo "=== /etc/passwd 소유자·권한 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: /etc/passwd 경로=/etc/passwd, 권한 허용값=644, 허용 소유자:그룹=root:root"

# 점검 항목 1: /etc/passwd 파일 존재 여부 확인
if [ ! -e /etc/passwd ]; then
  echo "1. /etc/passwd 파일 존재 여부"
  echo "   [FAIL] /etc/passwd 파일이 존재하지 않습니다."
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: /etc/passwd 파일이 존재하는지 확인하고 복구하세요."
  exit 1
else
  echo "1. /etc/passwd 파일 존재 여부"
  echo "   [PASS] /etc/passwd 파일이 존재합니다."
fi

# 점검 항목 2: /etc/passwd 파일 소유자 및 그룹 확인
owner_group=$(stat -c '%U:%G' /etc/passwd)
if [ "$owner_group" != "root:root" ]; then
  echo "2. /etc/passwd 파일 소유자 및 그룹 확인"
  echo "   [FAIL] 현재 소유자:그룹은 $owner_group 입니다."
else
  echo "2. /etc/passwd 파일 소유자 및 그룹 확인"
  echo "   [PASS] 소유자:그룹이 root:root 입니다."
fi

# 점검 항목 3: /etc/passwd 파일 권한 확인
permissions=$(stat -c '%a' /etc/passwd)
if [ "$permissions" -ne 644 ]; then
  echo "3. /etc/passwd 파일 권한 확인"
  echo "   [FAIL] 현재 권한은 $permissions 입니다."
else
  echo "3. /etc/passwd 파일 권한 확인"
  echo "   [PASS] 권한이 644 입니다."
fi

# 점검 결과 요약
echo "=== 점검 결과 요약 ==="
issues=0
if [ "$owner_group" != "root:root" ]; then
  issues=$((issues + 1))
fi
if [ "$permissions" -ne 644 ]; then
  issues=$((issues + 1))
fi

if [ $issues -eq 0 ]; then
  echo "전체 평가: Good"
  echo "발견된 문제: 0개"
  echo "권장 조치사항: 없음"
else
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: $issues 개"
  echo "권장 조치사항: /etc/passwd 파일의 소유자, 그룹 및 권한을 root:root, 644로 설정하세요."
fi
```