# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_50c1c2bc-0ff1-4273-845b-44badff8bc4f
# Generated: 2025-10-13T07:21:58.133Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-13-16h
# - Full Path: /2025-10-13-16h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 계정 잠금 임계값 설정 점검 스크립트 ===
# ID: U-03
# 생성 시간: $(date)
# 설정값 요약: PAM 경로=/etc/pam.d/system-auth, 계정 잠금 임계값=5

PAM_FILE="/etc/pam.d/system-auth"
LOCKOUT_THRESHOLD=5

# 점검 결과 초기화
RESULTS=()
OVERALL_STATUS="Good"
ISSUE_COUNT=0

# PAM 파일 존재 여부 점검
if [ ! -f "$PAM_FILE" ]; then
    RESULTS+=("PAM 파일이 존재하지 않습니다: $PAM_FILE")
    OVERALL_STATUS="Vulnerable"
    ISSUE_COUNT=$((ISSUE_COUNT + 1))
else
    # 계정 잠금 임계값 설정 점검
    if grep -q "deny=$LOCKOUT_THRESHOLD" "$PAM_FILE"; then
        RESULTS+=("계정 잠금 임계값이 올바르게 설정되어 있습니다: $LOCKOUT_THRESHOLD")
    else
        RESULTS+=("계정 잠금 임계값이 설정되어 있지 않거나 잘못 설정되어 있습니다.")
        OVERALL_STATUS="Vulnerable"
        ISSUE_COUNT=$((ISSUE_COUNT + 1))
    fi
fi

# 결과 리포트 출력
echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: PAM 경로=$PAM_FILE, 계정 잠금 임계값=$LOCKOUT_THRESHOLD"

# 점검 결과 출력
for i in "${!RESULTS[@]}"; do
    echo "$((i + 1)). ${RESULTS[$i]}"
    if [[ ${RESULTS[$i]} == *"올바르게 설정되어 있습니다"* ]]; then
        echo "   [PASS]"
    else
        echo "   [FAIL]"
    fi
done

# 요약 섹션
echo "=== 점검 결과 요약 ==="
echo "전체 평가: $OVERALL_STATUS"
echo "발견된 문제: $ISSUE_COUNT 개"
if [ "$OVERALL_STATUS" == "Vulnerable" ]; then
    echo "권장 조치사항: 계정 잠금 임계값을 $LOCKOUT_THRESHOLD 로 설정하십시오."
fi
```