# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: 7a49d56d-49e7-4794-9044-104deef25884_1759378911203
# Generated: 2025-10-02T04:21:51.610Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: Script Completion Forcer
#
# File Information:
# - File Name: OS--Unknown--OSLinux.sh
# - Time-based Folder: 2025-10-02-13h
# - Full Path: /2025-10-02-13h/OS--Unknown--OSLinux.sh
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === 패스워드 복잡성 정책 설정 점검 스크립트 ===
# 스크립트 ID: U-02
# 카테고리: 패스워드정책
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# 사용자 설정 요약:
# - PAM system-auth 경로: /etc/pam.d/system-auth
# - pwquality.conf 경로: /etc/security/pwquality.conf
# - 최소 길이 요구사항: 8

# 점검 결과를 저장할 변수 초기화
RESULTS=()
ISSUES=0

# 점검 시간 출력
echo "=== 패스워드 복잡성 정책 설정 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: PAM system-auth 경로: /etc/pam.d/system-auth, pwquality.conf 경로: /etc/security/pwquality.conf, 최소 길이 요구사항: 8"

# PAM system-auth 파일 점검
if [ -f /etc/pam.d/system-auth ]; then
    # 최소 길이 설정 확인
    if grep -q "pam_pwquality.so" /etc/pam.d/system-auth; then
        LENGTH=$(grep "pam_pwquality.so" /etc/pam.d/system-auth | grep -oP 'minlen=\K\d+')
        if [ "$LENGTH" -ge 8 ]; then
            RESULTS+=("1. PAM system-auth 최소 길이 설정: PASS")
        else
            RESULTS+=("1. PAM system-auth 최소 길이 설정: FAIL (현재 설정: $LENGTH)")
            ISSUES=$((ISSUES + 1))
        fi
    else
        RESULTS+=("1. PAM system-auth에 pam_pwquality.so 설정 없음: FAIL")
        ISSUES=$((ISSUES + 1))
    fi
else
    RESULTS+=("1. PAM system-auth 파일 없음 또는 권한 없음: FAIL")
    ISSUES=$((ISSUES + 1))
fi

# pwquality.conf 파일 점검
if [ -f /etc/security/pwquality.conf ]; then
    # 최소 길이 설정 확인
    LENGTH=$(grep -oP '^minlen=\K\d+' /etc/security/pwquality.conf)
    if [ "$LENGTH" -ge 8 ]; then
        RESULTS+=("2. pwquality.conf 최소 길이 설정: PASS")
    else
        RESULTS+=("2. pwquality.conf 최소 길이 설정: FAIL (현재 설정: $LENGTH)")
        ISSUES=$((ISSUES + 1))
    fi
else
    RESULTS+=("2. pwquality.conf 파일 없음 또는 권한 없음: FAIL")
    ISSUES=$((ISSUES + 1))
fi

# 점검 결과 출력
for RESULT in "${RESULTS[@]}"; do
    echo "$RESULT"
done

# 점검 결과 요약
echo "=== 점검 결과 요약 ==="
if [ "$ISSUES" -eq 0 ]; then
    echo "전체 평가: Good"
    echo "발견된 문제: 0개"
    echo "권장 조치사항: 모든 설정이 올바르게 구성되어 있습니다."
else
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: $ISSUES개"
    echo "권장 조치사항: 위의 FAIL 항목을 확인하고 설정을 수정하세요."
fi
```