# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759370264954_hzadtm4bo
# Generated: 2025-10-02T01:57:45.630Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-security-check-process.sh
# - Time-based Folder: 2025-10-02-10h
# - Full Path: /2025-10-02-10h/OS--보안-점검-대상--OSLinux-security-check-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: security-check-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === /etc/passwd 소유자·권한 점검 스크립트 ===
# 스크립트 ID: U-07
# 카테고리: 파일보안
# 생성 시간: $(date)
# 설정값 요약: 경로=/etc/passwd, 권한=644, 소유자:그룹=root:root

# 점검 시간
echo "=== /etc/passwd 소유자·권한 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: 경로=/etc/passwd, 권한=644, 소유자:그룹=root:root"
echo ""

# /etc/passwd 파일 존재 여부 확인
if [ ! -e /etc/passwd ]; then
  echo "1. /etc/passwd 파일 존재 확인"
  echo "   [FAIL] /etc/passwd 파일이 존재하지 않습니다."
  echo "=== 점검 결과 요약 ==="
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개"
  echo "권장 조치사항: /etc/passwd 파일이 존재하는지 확인하고, 시스템의 무결성을 점검하세요."
  exit 1
fi

# /etc/passwd 파일 권한 점검
actual_permissions=$(stat -c "%a" /etc/passwd)
if [ "$actual_permissions" -eq 644 ]; then
  echo "1. /etc/passwd 파일 권한 점검"
  echo "   [PASS] 파일 권한이 644로 설정되어 있습니다."
else
  echo "1. /etc/passwd 파일 권한 점검"
  echo "   [FAIL] 파일 권한이 $actual_permissions로 설정되어 있습니다. (권장: 644)"
fi

# /etc/passwd 파일 소유자 및 그룹 점검
actual_owner_group=$(stat -c "%U:%G" /etc/passwd)
if [ "$actual_owner_group" == "root:root" ]; then
  echo "2. /etc/passwd 파일 소유자 및 그룹 점검"
  echo "   [PASS] 파일 소유자 및 그룹이 root:root로 설정되어 있습니다."
else
  echo "2. /etc/passwd 파일 소유자 및 그룹 점검"
  echo "   [FAIL] 파일 소유자 및 그룹이 $actual_owner_group로 설정되어 있습니다. (권장: root:root)"
fi

# 점검 결과 요약
echo ""
echo "=== 점검 결과 요약 ==="
if [ "$actual_permissions" -eq 644 ] && [ "$actual_owner_group" == "root:root" ]; then
  echo "전체 평가: Good"
  echo "발견된 문제: 0개"
  echo "권장 조치사항: 없음"
else
  echo "전체 평가: Vulnerable"
  echo "발견된 문제: 1개 이상"
  echo "권장 조치사항: /etc/passwd 파일의 권한과 소유자:그룹을 권장 설정값으로 변경하세요."
fi
```