# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759304915131_bj0b3s1is
# Generated: 2025-10-01T07:48:35.812Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Unknown--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-01-16h
# - Full Path: /2025-10-01-16h/OS--Unknown--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === Root 계정 원격 접속 제한 점검 스크립트 ===
# 스크립트 ID: U-01
# 생성 시간: $(date)
# 설정값 요약:
# - SSH 설정 파일 경로: /etc/ssh/sshd_config
# - PAM 로그인 설정 파일 경로: /etc/pam.d/login
# - securetty 파일 경로: /etc/securetty
# - SSH 접속 제한 검사: 활성화
# - Telnet 접속 제한 검사: 활성화
# - Solaris CONSOLE 설정 확인: 활성화
# - AIX rlogin 설정 확인: 활성화
# - Linux 배포판: auto

# 점검 결과를 저장할 변수 초기화
RESULTS=()

# === 점검 로직 ===

# 1. SSH 설정 파일에서 Root 로그인 제한 확인
if [ -f /etc/ssh/sshd_config ]; then
    if grep -q "^PermitRootLogin no" /etc/ssh/sshd_config; then
        RESULTS+=("1. SSH Root 로그인 제한: PASS")
    else
        RESULTS+=("1. SSH Root 로그인 제한: FAIL - PermitRootLogin 설정 필요")
    fi
else
    RESULTS+=("1. SSH 설정 파일 없음: FAIL - /etc/ssh/sshd_config 파일을 찾을 수 없음")
fi

# 2. Telnet 접속 제한 확인 (securetty 파일)
if [ -f /etc/securetty ]; then
    if ! grep -q "^pts" /etc/securetty; then
        RESULTS+=("2. Telnet Root 로그인 제한: PASS")
    else
        RESULTS+=("2. Telnet Root 로그인 제한: FAIL - securetty 파일에서 pts 항목 제거 필요")
    fi
else
    RESULTS+=("2. securetty 파일 없음: FAIL - /etc/securetty 파일을 찾을 수 없음")
fi

# 3. Solaris CONSOLE 설정 확인
if [ -f /etc/default/login ]; then
    if grep -q "^CONSOLE=/dev/console" /etc/default/login; then
        RESULTS+=("3. Solaris CONSOLE 설정: PASS")
    else
        RESULTS+=("3. Solaris CONSOLE 설정: FAIL - /etc/default/login 파일에서 CONSOLE 설정 필요")
    fi
else
    RESULTS+=("3. Solaris CONSOLE 설정 파일 없음: FAIL - /etc/default/login 파일을 찾을 수 없음")
fi

# 4. AIX rlogin 설정 확인
if [ -f /etc/inetd.conf ]; then
    if grep -q "^#.*rlogin" /etc/inetd.conf; then
        RESULTS+=("4. AIX rlogin 설정: PASS")
    else
        RESULTS+=("4. AIX rlogin 설정: FAIL - /etc/inetd.conf 파일에서 rlogin 비활성화 필요")
    fi
else
    RESULTS+=("4. AIX rlogin 설정 파일 없음: FAIL - /etc/inetd.conf 파일을 찾을 수 없음")
fi

# === 결과 리포트 ===
echo "=== Root 계정 원격 접속 제한 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: SSH, Telnet, Solaris, AIX 설정 점검"

for result in "${RESULTS[@]}"; do
    echo "$result"
done

# === 점검 결과 요약 ===
echo "=== 점검 결과 요약 ==="
fail_count=$(printf "%s\n" "${RESULTS[@]}" | grep -c "FAIL")
if [ "$fail_count" -eq 0 ]; then
    echo "전체 평가: Good"
else
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: $fail_count 개"
    echo "권장 조치사항: 각 FAIL 항목에 대한 설정 수정 필요"
fi
```