# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_84067be5-9001-4d21-b306-cb86ca17d02f
# Generated: 2025-10-13T05:21:31.270Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-13-14h
# - Full Path: /2025-10-13-14h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 계정 잠금 임계값 설정 점검 스크립트 ===
# 스크립트 ID: U-03
# 생성 시간: $(date)
# 설정값 요약: PAM 경로=/etc/pam.d/system-auth, 계정 잠금 임계값=5, 배포판=debian

# PAM 시스템 인증 파일 경로
PAM_FILE="/etc/pam.d/system-auth"
# 계정 잠금 임계값
LOCKOUT_THRESHOLD=5
# 점검 결과 변수 초기화
RESULT=0
ISSUES=0

# 리눅스 배포판 확인
if [[ $(lsb_release -is) != "Debian" ]]; then
    echo "FAIL: 현재 시스템은 Debian이 아닙니다."
    RESULT=1
    ISSUES=$((ISSUES + 1))
else
    echo "PASS: 현재 시스템은 Debian입니다."
fi

# PAM 파일 존재 여부 확인
if [ ! -f "$PAM_FILE" ]; then
    echo "FAIL: PAM 파일이 존재하지 않습니다: $PAM_FILE"
    RESULT=1
    ISSUES=$((ISSUES + 1))
else
    echo "PASS: PAM 파일이 존재합니다: $PAM_FILE"
    
    # 기존 설정 백업
    cp "$PAM_FILE" "${PAM_FILE}.bak"
    echo "INFO: 기존 PAM 파일 백업 완료: ${PAM_FILE}.bak"
    
    # 계정 잠금 임계값 설정 확인
    if grep -q "auth required pam_tally2.so" "$PAM_FILE"; then
        if grep -q "deny=$LOCKOUT_THRESHOLD" "$PAM_FILE"; then
            echo "PASS: 계정 잠금 임계값이 올바르게 설정되어 있습니다: $LOCKOUT_THRESHOLD"
        else
            echo "FAIL: 계정 잠금 임계값이 설정되어 있지 않거나 잘못 설정되었습니다."
            RESULT=1
            ISSUES=$((ISSUES + 1))
        fi
    else
        echo "FAIL: PAM 설정에서 pam_tally2.so가 누락되었습니다."
        RESULT=1
        ISSUES=$((ISSUES + 1))
    fi
fi

# 결과 리포트
echo "=== 계정 잠금 임계값 설정 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: PAM 경로=$PAM_FILE, 계정 잠금 임계값=$LOCKOUT_THRESHOLD"

# 점검 항목 결과 출력
if [ $RESULT -eq 0 ]; then
    echo "전체 평가: Good"
else
    echo "전체 평가: Vulnerable"
fi

echo "발견된 문제: $ISSUES 개"
if [ $ISSUES -gt 0 ]; then
    echo "권장 조치사항: PAM 설정을 검토하고 필요한 경우 수정하세요."
fi
```