# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_a255af6c-c64e-42fd-b36a-9d1df3a80336
# Generated: 2025-10-13T05:06:45.807Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-13-14h
# - Full Path: /2025-10-13-14h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === 파일/디렉터리 소유자 설정 점검 스크립트 ===
# 스크립트 ID: U-06
# 생성 시간: $(date)
# 설정값 요약: 중요 파일 목록 - /etc/passwd, /etc/shadow, /etc/group
# 허용 소유자:그룹 - root:root
# Linux 배포판 - suse

# 점검할 파일 목록
files=("/etc/passwd" "/etc/shadow" "/etc/group")
# 허용되는 소유자 및 그룹
allowed_owner="root"
allowed_group="root"

# 결과 변수 초기화
result=0
report=""

# 점검 로직
for file in "${files[@]}"; do
    if [[ -e "$file" ]]; then  # 파일 존재 여부 확인
        # 파일의 소유자 및 그룹 정보 가져오기
        owner=$(stat -c "%U" "$file")
        group=$(stat -c "%G" "$file")
        
        # 소유자 및 그룹 점검
        if [[ "$owner" == "$allowed_owner" && "$group" == "$allowed_group" ]]; then
            report+="$(basename "$file"): [PASS] 소유자 및 그룹이 올바릅니다.\n"
        else
            report+="$(basename "$file"): [FAIL] 소유자: $owner, 그룹: $group (허용: $allowed_owner:$allowed_group)\n"
            result=1
        fi
    else
        report+="$(basename "$file"): [FAIL] 파일이 존재하지 않거나 접근할 수 없습니다.\n"
        result=1
    fi
done

# 결과 리포트 출력
echo -e "=== 파일/디렉터리 소유자 설정 점검 결과 ==="
echo -e "점검 시간: $(date)"
echo -e "설정 적용: 중요 파일 목록 - ${files[*]}, 허용 소유자:그룹 - $allowed_owner:$allowed_group\n"

# 점검 결과 출력
echo -e "$report"

# 점검 결과 요약
if [[ $result -eq 0 ]]; then
    echo -e "=== 점검 결과 요약 ==="
    echo -e "전체 평가: Good"
    echo -e "발견된 문제: 0개"
    echo -e "권장 조치사항: 없음"
else
    echo -e "=== 점검 결과 요약 ==="
    echo -e "전체 평가: Vulnerable"
    echo -e "발견된 문제: 1개 이상"
    echo -e "권장 조치사항: 소유자 및 그룹을 $allowed_owner:$allowed_group로 변경하십시오."
fi
```