# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_b1466fae-46a8-4718-9f9d-9486b48cd048
# Generated: 2025-10-13T05:11:57.544Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-10-13-14h
# - Full Path: /2025-10-13-14h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === /etc/hosts 소유자·권한 점검 스크립트 ===
# 스크립트 ID: U-09
# 생성 시간: $(date)
# 설정 적용: /etc/hosts 경로, 권한 644, 소유자:그룹 root:root

# 점검할 파일 경로
FILE="/etc/hosts"
# 허용 권한 및 소유자 설정
ALLOWED_PERMISSIONS="644"
ALLOWED_OWNER="root"
ALLOWED_GROUP="root"

# 점검 결과 초기화
RESULT="Good"
ISSUES=0

# 파일 존재 여부 점검
if [ ! -e "$FILE" ]; then
    echo "=== 점검 결과 ==="
    echo "점검 시간: $(date)"
    echo "설정 적용: /etc/hosts 경로, 권한 $ALLOWED_PERMISSIONS, 소유자:그룹 $ALLOWED_OWNER:$ALLOWED_GROUP"
    echo "1. /etc/hosts 파일 존재 여부"
    echo "   FAIL: /etc/hosts 파일이 존재하지 않습니다."
    echo "=== 점검 결과 요약 ==="
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: 1개"
    echo "권장 조치사항: /etc/hosts 파일을 생성하십시오."
    exit 1
fi

# 파일 권한 점검
CURRENT_PERMISSIONS=$(stat -c "%a" "$FILE")
if [ "$CURRENT_PERMISSIONS" -ne "$ALLOWED_PERMISSIONS" ]; then
    echo "1. /etc/hosts 파일 권한 점검"
    echo "   FAIL: 현재 권한은 $CURRENT_PERMISSIONS 이며, 허용 권한은 $ALLOWED_PERMISSIONS 입니다."
    RESULT="Vulnerable"
    ISSUES=$((ISSUES + 1))
else
    echo "1. /etc/hosts 파일 권한 점검"
    echo "   PASS: 현재 권한은 $CURRENT_PERMISSIONS 입니다."
fi

# 파일 소유자 및 그룹 점검
CURRENT_OWNER=$(stat -c "%U" "$FILE")
CURRENT_GROUP=$(stat -c "%G" "$FILE")
if [ "$CURRENT_OWNER" != "$ALLOWED_OWNER" ] || [ "$CURRENT_GROUP" != "$ALLOWED_GROUP" ]; then
    echo "2. /etc/hosts 파일 소유자 및 그룹 점검"
    echo "   FAIL: 현재 소유자는 $CURRENT_OWNER, 그룹은 $CURRENT_GROUP 이며, 허용 소유자는 $ALLOWED_OWNER, 그룹은 $ALLOWED_GROUP 입니다."
    RESULT="Vulnerable"
    ISSUES=$((ISSUES + 1))
else
    echo "2. /etc/hosts 파일 소유자 및 그룹 점검"
    echo "   PASS: 현재 소유자는 $CURRENT_OWNER, 그룹은 $CURRENT_GROUP 입니다."
fi

# === 점검 결과 요약 ===
echo "=== 점검 결과 요약 ==="
echo "전체 평가: $RESULT"
echo "발견된 문제: $ISSUES 개"
if [ "$ISSUES" -gt 0 ]; then
    echo "권장 조치사항: 권한 및 소유자 설정을 확인하고 수정하십시오."
fi
```