# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759199438084_dy7l917n7
# Generated: 2025-09-30T02:30:38.199Z
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# Configuration:
# - Target OS: Linux
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash
# U-02: Password complexity setting check (simple version)
# 생성 시간: $(date)
# 설정값 요약: targetOS=Linux, outputFormat=bash, 최소 길이 요구사항=8

echo "=== 패스워드 복잡성 정책 설정 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: [targetOS: Linux, 최소 길이 요구사항: 8]"

# PAM 설정 파일 경로
PAM_CONFIG="/etc/pam.d/system-auth"
# pwquality 설정 파일 경로
PWQUALITY_CONFIG="/etc/security/pwquality.conf"

# 점검 결과 변수 초기화
RESULTS=()
PROBLEMS=0

# 1. PAM 복잡성 설정 점검
if [ -f "$PAM_CONFIG" ]; then
    echo "1. PAM 복잡성 설정 점검:"
    if grep -q "pam_pwquality.so" "$PAM_CONFIG"; then
        RESULTS+=("[PASS] pwquality 모듈이 사용 중입니다.")
    elif grep -q "pam_cracklib.so" "$PAM_CONFIG"; then
        RESULTS+=("[PASS] cracklib 모듈이 사용 중입니다.")
    else
        RESULTS+=("[FAIL] 복잡성 모듈이 발견되지 않았습니다.")
        PROBLEMS=$((PROBLEMS + 1))
    fi
else
    RESULTS+=("[FAIL] PAM 설정 파일이 존재하지 않습니다: $PAM_CONFIG")
    PROBLEMS=$((PROBLEMS + 1))
fi

# 2. pwquality.conf 설정 점검
if [ -f "$PWQUALITY_CONFIG" ]; then
    echo "2. 복잡성 정책 점검:"
    MIN_LEN=$(grep "^minlen" "$PWQUALITY_CONFIG" | cut -d= -f2)
    if [ "$MIN_LEN" -ge 8 ]; then
        RESULTS+=("[PASS] 최소 길이: $MIN_LEN")
    else
        RESULTS+=("[FAIL] 최소 길이가 부족합니다: $MIN_LEN")
        PROBLEMS=$((PROBLEMS + 1))
    fi
else
    RESULTS+=("[FAIL] pwquality 설정 파일이 존재하지 않습니다: $PWQUALITY_CONFIG")
    PROBLEMS=$((PROBLEMS + 1))
fi

# 점검 결과 출력
for RESULT in "${RESULTS[@]}"; do
    echo "   $RESULT"
done

# 전체 점검 결과 요약
echo "=== 점검 결과 요약 ==="
if [ "$PROBLEMS" -eq 0 ]; then
    echo "전체 평가: Good"
else
    echo "전체 평가: Vulnerable"
    echo "발견된 문제: $PROBLEMS 개"
    echo "권장 조치사항: PAM 설정 파일에 복잡성 모듈 추가 및 pwquality.conf의 최소 길이 설정을 확인하세요."
fi
```