# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759199337446_gzfggznpg
# Generated: 2025-09-30T02:28:57.824Z
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === Root 계정 원격 접속 제한 점검 결과 ===
# 점검 시간: 현재 시간
# 설정 적용: SSH 설정 파일 경로, PAM 로그인 설정 파일 경로, securetty 파일 경로

CHECK_TIME=$(date)
SSH_CONFIG="/etc/ssh/sshd_config"
PAM_LOGIN_CONFIG="/etc/pam.d/login"
SECURETTY_CONFIG="/etc/securetty"
RESULTS=()
ISSUES=0

# SSH 설정 파일 점검
if [ -f "$SSH_CONFIG" ]; then
    if grep -q "^PermitRootLogin no" "$SSH_CONFIG"; then
        RESULTS+=("1. SSH 설정: root 로그인 제한 설정됨 [PASS]")
    else
        RESULTS+=("1. SSH 설정: root 로그인 제한 설정되지 않음 [FAIL]")
        ISSUES=$((ISSUES + 1))
    fi
else
    RESULTS+=("1. SSH 설정: 파일이 존재하지 않음 [FAIL]")
    ISSUES=$((ISSUES + 1))
fi

# PAM 로그인 설정 파일 점검
if [ -f "$PAM_LOGIN_CONFIG" ]; then
    if grep -q "auth required pam_nologin.so" "$PAM_LOGIN_CONFIG"; then
        RESULTS+=("2. PAM 로그인 설정: nologin 설정됨 [PASS]")
    else
        RESULTS+=("2. PAM 로그인 설정: nologin 설정되지 않음 [FAIL]")
        ISSUES=$((ISSUES + 1))
    fi
else
    RESULTS+=("2. PAM 로그인 설정: 파일이 존재하지 않음 [FAIL]")
    ISSUES=$((ISSUES + 1))
fi

# securetty 파일 점검
if [ -f "$SECURETTY_CONFIG" ]; then
    if grep -q "^tty[0-9]*" "$SECURETTY_CONFIG"; then
        RESULTS+=("3. securetty 설정: tty 설정됨 [PASS]")
    else
        RESULTS+=("3. securetty 설정: tty 설정되지 않음 [FAIL]")
        ISSUES=$((ISSUES + 1))
    fi
else
    RESULTS+=("3. securetty 설정: 파일이 존재하지 않음 [FAIL]")
    ISSUES=$((ISSUES + 1))
fi

# === 점검 결과 요약 ===
if [ $ISSUES -eq 0 ]; then
    OVERALL_STATUS="Good"
else
    OVERALL_STATUS="Vulnerable"
fi

# 결과 출력
echo "=== Root 계정 원격 접속 제한 점검 결과 ==="
echo "점검 시간: $CHECK_TIME"
echo "설정 적용: SSH 설정 파일 경로: $SSH_CONFIG, PAM 로그인 설정 파일 경로: $PAM_LOGIN_CONFIG, securetty 파일 경로: $SECURETTY_CONFIG"
echo ""

for RESULT in "${RESULTS[@]}"; do
    echo "$RESULT"
done

echo ""
echo "=== 점검 결과 요약 ==="
echo "전체 평가: $OVERALL_STATUS"
echo "발견된 문제: $ISSUES 개"
echo "권장 조치사항: root 계정의 원격 로그인을 제한하도록 설정을 검토하세요."
```