# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759213145181_235xsf4yy
# Generated: 2025-09-30T06:19:06.896Z
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === 패스워드 복잡성 정책 설정 점검 스크립트 ===
# 스크립트 ID: U-02
# 카테고리: 패스워드정책
# 난이도: medium
# 위험도: medium
# 생성 시간: $(date)
# 설정값 요약: PASS_MAX_DAYS <= 180, 최소 길이 8

# 점검 시간
echo "=== 패스워드 복잡성 정책 설정 점검 결과 ==="
echo "점검 시간: $(date)"

# 점검 항목 1: PASS_MAX_DAYS 설정 확인
echo "1. PASS_MAX_DAYS 설정 확인"

# /etc/login.defs 파일에서 PASS_MAX_DAYS 값 확인
if [ -r /etc/login.defs ]; then
    PASS_MAX_DAYS=$(grep "^PASS_MAX_DAYS" /etc/login.defs | awk '{print $2}')
    if [ -z "$PASS_MAX_DAYS" ]; then
        echo "   [FAIL] PASS_MAX_DAYS 설정이 없습니다."
    elif [ "$PASS_MAX_DAYS" -le 180 ]; then
        echo "   [PASS] PASS_MAX_DAYS 설정이 적절합니다: $PASS_MAX_DAYS"
    else
        echo "   [FAIL] PASS_MAX_DAYS 설정이 너무 큽니다: $PASS_MAX_DAYS"
    fi
else
    echo "   [FAIL] /etc/login.defs 파일을 읽을 수 없습니다."
fi

# 점검 항목 2: 각 사용자 계정의 패스워드 사용 기간 확인
echo "2. 사용자 계정의 패스워드 사용 기간 확인"

# 모든 사용자 계정에 대해 패스워드 사용 기간 확인
awk -F: '{ print $1 }' /etc/passwd | while read -r user; do
    if [ "$user" != "root" ]; then
        user_max_days=$(chage -l "$user" | grep "Maximum number of days between password change" | awk -F: '{print $2}' | xargs)
        if [ -z "$user_max_days" ]; then
            echo "   [FAIL] $user: 패스워드 사용 기간 정보를 가져올 수 없습니다."
        elif [ "$user_max_days" -le 180 ]; then
            echo "   [PASS] $user: 패스워드 사용 기간이 적절합니다: $user_max_days 일"
        else
            echo "   [FAIL] $user: 패스워드 사용 기간이 너무 깁니다: $user_max_days 일"
        fi
    fi
done

# 점검 결과 요약
echo "=== 점검 결과 요약 ==="
echo "전체 평가: $(if [ "$PASS_MAX_DAYS" -le 180 ]; then echo "Good"; else echo "Vulnerable"; fi)"
echo "발견된 문제: $(grep -c "[FAIL]" <<< $(echo "$PASS_MAX_DAYS"))개"
echo "권장 조치사항: PASS_MAX_DAYS를 180일 이하로 설정하고, 각 사용자 계정의 패스워드 사용 기간을 확인하세요."
```