# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759198379892_6zd8i3fm7
# Generated: 2025-09-30T02:13:00.071Z
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# Configuration:
# - Target OS: Linux
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash
# U-01: Root account remote access restriction check script
# Generated: $(date)

echo "=== Root 계정 원격 접속 제한 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: [SSH 설정 파일: /etc/ssh/sshd_config, PAM 로그인 설정 파일: /etc/pam.d/login, securetty 파일: /etc/securetty]"
echo ""

# OS 타입 확인
OS_TYPE=$(uname -s)
echo "OS 타입: $OS_TYPE"

# 결과 변수 초기화
RESULT="Good"
ISSUES=()

# SSH 설정 점검
if [ -f "/etc/ssh/sshd_config" ]; then
    echo "1. SSH 설정 점검"
    PERMIT_ROOT=$(grep -E "^PermitRootLogin" /etc/ssh/sshd_config | awk '{print $2}')
    
    if [ "$PERMIT_ROOT" = "no" ]; then
        echo "   [PASS] SSH root 로그인 차단됨"
    else
        echo "   [FAIL] SSH root 로그인 허용됨"
        RESULT="Vulnerable"
        ISSUES+=("SSH PermitRootLogin이 'no'로 설정되지 않음")
    fi
else
    echo "1. SSH 설정 파일을 찾을 수 없음"
    RESULT="Vulnerable"
    ISSUES+=("SSH 설정 파일이 존재하지 않음")
fi

echo ""

# Telnet 설정 점검 (Linux 전용)
if [ "$OS_TYPE" = "Linux" ]; then
    echo "2. Linux Telnet 설정 점검"
    
    # PAM 설정 점검
    if [ -f "/etc/pam.d/login" ]; then
        if grep -q "pam_securetty.so" /etc/pam.d/login; then
            echo "   [PASS] PAM securetty 모듈이 활성화됨"
        else
            echo "   [FAIL] PAM securetty 모듈이 비활성화됨"
            RESULT="Vulnerable"
            ISSUES+=("PAM securetty 모듈이 활성화되지 않음")
        fi
    else
        echo "2. PAM 로그인 설정 파일을 찾을 수 없음"
        RESULT="Vulnerable"
        ISSUES+=("PAM 로그인 설정 파일이 존재하지 않음")
    fi
    
    # securetty 파일 점검
    if [ -f "/etc/securetty" ]; then
        PTS_COUNT=$(grep -E "^pts/" /etc/securetty | wc -l)
        if [ $PTS_COUNT -eq 0 ]; then
            echo "   [PASS] securetty에 pts 설정이 없음"
        else
            echo "   [FAIL] securetty에 pts 설정이 존재함"
            RESULT="Vulnerable"
            ISSUES+=("securetty 파일에 pts 설정이 존재함")
        fi
    else
        echo "2. securetty 파일을 찾을 수 없음"
        RESULT="Vulnerable"
        ISSUES+=("securetty 파일이 존재하지 않음")
    fi
fi

echo ""
echo "=== 점검 결과 요약 ==="
echo "전체 평가: $RESULT"

if [ "$RESULT" = "Vulnerable" ]; then
    echo "발견된 문제:"
    for issue in "${ISSUES[@]}"; do
        echo "  - $issue"
    done
    echo ""
    echo "권장 조치사항:"
    echo "  1. SSH 설정: 'PermitRootLogin no'로 설정"
    echo "  2. Telnet 접근 제한 설정 적용"
    echo "  3. 설정 변경 후 서비스 재시작"
fi

echo "점검 완료 시간: $(date)"
```