# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759203898495_qyzmnk35f
# Generated: 2025-09-30T03:44:58.869Z
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === Root 디렉토리 보안 설정 점검 스크립트 ===
# 스크립트 ID: U-05
# 생성 시간: $(date)
# 설정값 요약: 허용 가능한 Root 홈 디렉토리 권한: 700, 750
# PATH에서 현재 디렉토리(.) 검사: 활성화
# 검사할 Shell 설정 파일: /root/.bashrc, /root/.profile
# 운영체제: Linux

# 점검 결과 변수 초기화
result=0
issues=0
report=""

# 함수: 점검 결과 추가
add_report() {
    report+="$1\n"
}

# 1. Root 홈 디렉토리 권한 점검
root_home_perm=$(stat -c "%a" /root)
if [[ "$root_home_perm" == "700" || "$root_home_perm" == "750" ]]; then
    add_report "Root 홈 디렉토리 권한: $root_home_perm [PASS]"
else
    add_report "Root 홈 디렉토리 권한: $root_home_perm [FAIL]"
    issues=$((issues + 1))
fi

# 2. 현재 디렉토리(.) PATH 포함 여부 점검
if echo "$PATH" | grep -q "\."; then
    add_report "현재 디렉토리(.)가 PATH에 포함되어 있습니다. [FAIL]"
    issues=$((issues + 1))
else
    add_report "현재 디렉토리(.)가 PATH에 포함되어 있지 않습니다. [PASS]"
fi

# 3. Shell 설정 파일 점검
for file in /root/.bashrc /root/.profile; do
    if [[ -e "$file" ]]; then
        file_perm=$(stat -c "%a" "$file")
        if [[ "$file_perm" == "600" || "$file_perm" == "644" ]]; then
            add_report "$file 권한: $file_perm [PASS]"
        else
            add_report "$file 권한: $file_perm [FAIL]"
            issues=$((issues + 1))
        fi
    else
        add_report "$file 파일이 존재하지 않습니다. [FAIL]"
        issues=$((issues + 1))
    fi
done

# === 점검 결과 요약 ===
if [[ $issues -eq 0 ]]; then
    overall_status="Good"
else
    overall_status="Vulnerable"
fi

# 결과 출력
echo -e "=== Root 디렉토리 보안 설정 점검 결과 ==="
echo -e "점검 시간: $(date)"
echo -e "설정 적용: [허용 가능한 Root 홈 디렉토리 권한: 700, 750, 현재 디렉토리(.) 검사: 활성화, 검사할 Shell 설정 파일: /root/.bashrc, /root/.profile]\n"
echo -e "$report"
echo -e "=== 점검 결과 요약 ==="
echo -e "전체 평가: $overall_status"
echo -e "발견된 문제: $issues 개"
echo -e "권장 조치사항: Root 홈 디렉토리 권한을 700 또는 750으로 설정하고, 현재 디렉토리를 PATH에서 제거하며, Shell 설정 파일 권한을 600 또는 644로 설정하세요."
```