# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: script_1759199281653_vvdl1eup6
# Generated: 2025-09-30T02:28:01.798Z
# Script Type: OS-Linux
# Target Product: Unknown
# Generated By: NCU Script Generator User
#
# Configuration:
# - Target OS: 
# - Process Name: 
# - Config Path: 
# - Account Name: 
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: 
# Fail Condition: 
#
# ========================================

```bash
#!/bin/bash

# === Root 계정 원격 접속 제한 점검 결과 ===
# 점검 시간: 현재 시간
# 설정 적용: SSH 설정 파일, PAM 로그인 설정 파일, securetty 파일 경로

echo "점검 시간: $(date)"
echo "설정 적용: SSH 설정 파일 경로: /etc/ssh/sshd_config, PAM 로그인 설정 파일 경로: /etc/pam.d/login, securetty 파일 경로: /etc/securetty"

# 초기 상태 변수
status="Good"
issue_count=0

# 1. SSH 설정 파일 점검
if [ -f /etc/ssh/sshd_config ]; then
    if grep -q "^PermitRootLogin no" /etc/ssh/sshd_config; then
        echo "1. SSH 설정: root 로그인 제한 설정 확인"
        echo "   [PASS] root 로그인 제한이 설정되어 있습니다."
    else
        echo "1. SSH 설정: root 로그인 제한 설정 확인"
        echo "   [FAIL] root 로그인 제한이 설정되어 있지 않습니다."
        status="Vulnerable"
        issue_count=$((issue_count + 1))
    fi
else
    echo "1. SSH 설정: /etc/ssh/sshd_config 파일이 존재하지 않습니다."
    echo "   [FAIL] SSH 설정 파일을 찾을 수 없습니다."
    status="Vulnerable"
    issue_count=$((issue_count + 1))
fi

# 2. PAM 로그인 설정 파일 점검
if [ -f /etc/pam.d/login ]; then
    if grep -q "auth required pam_nologin.so" /etc/pam.d/login; then
        echo "2. PAM 로그인 설정: root 로그인 제한 설정 확인"
        echo "   [PASS] PAM 로그인 제한이 설정되어 있습니다."
    else
        echo "2. PAM 로그인 설정: root 로그인 제한 설정 확인"
        echo "   [FAIL] PAM 로그인 제한이 설정되어 있지 않습니다."
        status="Vulnerable"
        issue_count=$((issue_count + 1))
    fi
else
    echo "2. PAM 로그인 설정: /etc/pam.d/login 파일이 존재하지 않습니다."
    echo "   [FAIL] PAM 로그인 설정 파일을 찾을 수 없습니다."
    status="Vulnerable"
    issue_count=$((issue_count + 1))
fi

# 3. securetty 파일 점검
if [ -f /etc/securetty ]; then
    if grep -q "^tty[0-9]*$" /etc/securetty; then
        echo "3. securetty 설정: root 로그인 허용 TTY 확인"
        echo "   [PASS] securetty 설정이 적절합니다."
    else
        echo "3. securetty 설정: root 로그인 허용 TTY 확인"
        echo "   [FAIL] securetty 설정이 적절하지 않습니다."
        status="Vulnerable"
        issue_count=$((issue_count + 1))
    fi
else
    echo "3. securetty 설정: /etc/securetty 파일이 존재하지 않습니다."
    echo "   [FAIL] securetty 파일을 찾을 수 없습니다."
    status="Vulnerable"
    issue_count=$((issue_count + 1))
fi

# === 점검 결과 요약 ===
echo "=== 점검 결과 요약 ==="
echo "전체 평가: $status"
echo "발견된 문제: $issue_count 개"
if [ "$issue_count" -gt 0 ]; then
    echo "권장 조치사항: root 로그인 제한을 설정하고, 관련 파일을 검토하세요."
else
    echo "권장 조치사항: 모든 설정이 적절합니다."
fi
```